### ISSUE TITLE
How to choose the best lambda?

### ISSUE THREAD

**Issue by WuyangFF95** [danro9685/SparseSignatures#11]
Hi @danro9685 ,

I was trying to use your package, but one key issue is that I cannot choose a proper number of lambda.

In the example provided by your vignette, you let the software to run `**nmf.lassoCV()**` with 3 lambda values (0.05, 0.10, 0.15), and you picked the best one (0.10). But there are certain cases scenarios that the best lambda may fall beyond these 3.

So is it necessary to test for more lambda values (e.g. 0.20, 0.30?) And can you briefly explain the meaning of "lambda" here? Thanks!

**Comment by danro9685** [comment]
Dear @WuyangFF95, 

you are correct: the range for lambda depends on the data and can vary from 0 to 1. 

You will need to estimate the range from your data, to do so we also provide to function evaluate.lambda.range, namely to evaluate the performance for a fixed number of signature and a range of values for lambda. You can evaluate the maximum value of lambda before you have a drop in likelihood. 

I am happy to assist you further if you have more questions. 

Best, 
Daniele
