### ISSUE TITLE
Error in match(x, table, nomatch = 0L) : 'match' requires vector arguments

### ISSUE THREAD

**Issue by danro9685** [danro9685/SparseSignatures#16]
Error happening only in check example (while it works when building vignette). 
The problem should be related to dependencies of function dcast, in file data.import.R, line 87

**Comment by luca-dex** [comment]
As reported by @vodkatad , in `import.trinucleotides.counts`, when running

```R
data$ref %in% c("C","T")
```

in results in

```R
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
```

So data should be conterted into vector
