### ISSUE TITLE
R release requriement needn't >4.1.0

### ISSUE THREAD

**Issue by wangshun1121** [danro9685/SparseSignatures#22]
Here is R release requirement in the DESCRIPTION file of this R package:

https://github.com/danro9685/SparseSignatures/blob/8250f853606c2147a041f83570041475bea4c24a/DESCRIPTION#L16

I cloned this git repo, and modified R release to 'R (>= 3.6.0)' , and I managed to install under R 3.6.3 using `devtools::install()`. I think R 4.1 release is not needed for this package.

**Comment by danro9685** [comment]
Dear @wangshun1121, 

thanks for the tip. 
While not necessary, a more recent release is still preferable. 

All the best, 
Daniele
