### ISSUE TITLE
Running SparseSig Singularity container

### ISSUE THREAD

**Issue by kdavydzenka** [danro9685/SparseSignatures#25]
Hello,

I'm having an issue running your Singularity container deposited on : https://depot.galaxyproject.org/singularity/bioconductor-sparsesignatures%3A2.12.0--r43hdfd78af_0
It doesn't find the packages of the reference genome inside the container: "BSgenome.Hsapiens.1000genomes.hs37d5", "BSgenome.Hsapiens.UCSC.hg38" .

**Comment by danro9685** [comment]
Dear @Katerina10-cloud,
We are not the ones uploading these packages on Singularity, but my guess is that it was not updated to the latest Bioconductor version, I know in Bioconductor they recently updated the BSgenome packages.
I am sorry I cannot update it, but if you need help running the tool from R, I can provide support.
All the best,
Daniele Ramazzotti
