### ISSUE TITLE
Using SparseSignatures in R 3.4.0 

### ISSUE THREAD

**Issue by mishugeb** [danro9685/SparseSignatures#8]
I have some issue with the installation of SparseSignatures. It installed quite well in my Laptop but I want to install that on our cluster.  The problem is the R version of our cluster is 3.4.0 and SparseSignatures requires 3.6.0. Is there any way I can install SparseSignatures in 3.4.0?

**Comment by danro9685** [comment]
Dear @mishugeb, 

first of all thanks for you interest in SparseSignatures! 
I would suggest you make an effort to update your R version (on the server) to the latest one, but if this is absolutely no possible, you can try to install SparseSignatures from the source I am attaching here. 

Best, 
Daniele 

[SparseSignatures_1.4.0.tar.gz](https://github.com/danro9685/SparseSignatures/files/3434375/SparseSignatures_1.4.0.tar.gz)
