### ISSUE TITLE
Exposure matrix

### ISSUE THREAD

**Issue by mishugeb** [danro9685/SparseSignatures#9]
I am trying to get the exposure matrix. May I know the method to get the exposure matrix? I couldn't find the method in the user guide.

**Comment by danro9685** [comment]
Dear @mishugeb, 

We name the exposure matrix, alpha. You can get it with these methods depending on which analysis you run: as.alpha, as.alpha.in.range. You will find more information in the manual of SparseSignatures. 

Best, 
Daniele
